# Generated by Django 2.2.4 on 2019-09-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(unique=True)),
                ('group_id', models.PositiveIntegerField()),
                ('account', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=200)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('sex', models.PositiveIntegerField(blank=True, null=True)),
                ('auth', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('field_id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('avatar', models.TextField(blank=True, null=True)),
                ('auth', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_group',
                'managed': True,
            },
        ),
    ]
