# Generated by Django 2.2.4 on 2019-09-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'managed': False},
        ),
    ]
